name: Upload to Yandex Object Storage

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          sudo mv ~/.yc/yc /usr/local/bin/yc
          yc config set token ${{ secrets.YC_ACCESS_KEY_ID }}

      - name: Upload files to Yandex Object Storage
        run: |
          # Укажите путь к вашим файлам или директории
          DIR_TO_UPLOAD="./*"
          
          # Целевая директория в бакете
          TARGET_DIR="proj/"

          # Загружаем файлы в Yandex Object Storage
          for file in $DIR_TO_UPLOAD; do
            yc storage cp $file s3://${{ secrets.YANDEX_BUCKET_NAME }}/$TARGET_DIR/$(basename $file)
          done
