name: Sync to Yandex Cloud

on:
  push:
    branches:
      - master  # Укажите вашу ветку

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Для доступа к истории коммитов

    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.YC_API_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_KEY_ID }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region ru-central1
        aws configure set default.s3.endpoint_url https://storage.yandexcloud.net
        aws configure set default.s3.signature_version s3v4

    - name: Get changed files
      run: |
        git diff --name-only HEAD^ HEAD
        files=$(git diff --name-only HEAD^ HEAD)
        echo "changed_files<<EOF" >> $GITHUB_OUTPUT
        echo "$files" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
        
    - name: Debug git diff
      run: |
        git diff --stat ${{ github.event.before }} ${{ github.event.after }}
        git diff ${{ github.event.before }} ${{ github.event.after }} --name-status

    - name: Upload files
      env:
        YC_BUCKET: ${{ secrets.YANDEX_BUCKET_NAME }}
        YC_DIR: "proj/"  # Замените на вашу директорию
      run: |
        if [ -z "${{ steps.changed-files.outputs.changed_files }}" ]; then
          echo "Нет измененных файлов"
          exit 0
        fi
        for file in ${{ steps.changed-files.outputs.changed_files }}; do
          if [ -f "$file" ]; then
            aws s3 cp "$file" "s3://${YC_BUCKET}/${YC_DIR}${file}"
          fi
        done
