name: Deploy to Yandex Cloud Storage

on:
  push:
    branches:
      - master  # Эта настройка запускает процесс при каждом пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: List files in current directory
      run: ls -la
      
    - name: Check if Python and SQL files exist
      run: |
        if ls *.py 1> /dev/null 2>&1; then
          echo "Python files found!"
        else
          echo "No Python files found!"
        fi
    
        if ls *.sql 1> /dev/null 2>&1; then
          echo "SQL files found!"
        else
          echo "No SQL files found!"
        fi

    - name: Upload Python and SQL files to Yandex Cloud Storage
      run: |
        # Создаем директорию для хранения файлов
        mkdir -p files
        
        # Копируем Python и SQL файлы в директорию
        cp *.py files/
        cp SQL_scripts.sql files/

        # Авторизуемся с помощью ключа сервисного аккаунта
        echo "${{ secrets.YC_CLOUD_KEY }}" > yc-key.json
        yc config set service-account-key yc-key.json
        yc config set folder-id https://console.yandex.cloud/folders/b1gu9p195r1it7d7ram0
        
        # Загрузка файлов в бакет
        yc storage cp files/* "s3://test-gringo-bucket/" --recursive
