name: Sync to Yandex Cloud

on:
  push:
    branches:
      - master  # Здесь укажите ветку, на которую хотите реагировать (например, main)

jobs:
  sync-files:
    runs-on: ubuntu-latest  # Используем Ubuntu в качестве операционной системы для выполнения задач

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Нужно, чтобы иметь доступ к полному списку коммитов (если потребуется)

    - name: Install Yandex Cloud CLI (yc)
      run: |
        # Установка Yandex Cloud CLI (yc)
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        exec -l $SHELL
        # Проверка установки
        yc --version

    - name: check installation
      run: |
        sudo mv /home/runner/yandex-cloud/bin/yc /usr/local/bin/yc
   
        

    - name: Configure Yandex Cloud CLI (yc)
      env:
        YC_BUCKET_NAME: ${{ secrets.YANDEX_BUCKET_NAME }}
      run: |
        # Настройка Yandex Cloud CLI
        echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > /home/runner/yc-service-account-key.json
        jq . /home/runner/yc-service-account-key.json
        yc config set service-account-key /home/runner/yc-service-account-key.json
        yc config set secret-key ${{ secrets.YC_SECRET_KEY }}
        # Мы не указываем cloud-id и folder-id, так как они обычно могут быть получены из ваших настроек в облаке (по умолчанию)
        yc config set cloud-id default
        yc config set folder-id default

    - name: Get changed files
      run: |
        # Получаем список измененных файлов в последнем коммите
        files=$(git diff --name-only HEAD^ HEAD)
        echo "changed_files=$files" >> $GITHUB_ENV  # Записываем измененные файлы в переменную окружения

    - name: Upload files to Yandex Cloud
      env:
        YC_BUCKET: ${{ secrets.YANDEX_BUCKET_NAME }}
        YC_DIR: "proj/"  # Замените на вашу директорию в бакете
        CHANGED_FILES: ${{ env.changed_files }}  # Переменная окружения с измененными файлами
      run: |
        if [ -z "$CHANGED_FILES" ]; then
          echo "Нет измененных файлов, пропускаем загрузку"
          exit 0
        fi
        # Загружаем каждый файл в Yandex Object Storage
        for file in $CHANGED_FILES; do
          if [ -f "$file" ]; then
            echo "Загружаем файл $file в Yandex Cloud Storage"
            yc storage cp "$file" "s3://${YC_BUCKET}/${YC_DIR}${file}"
          else
            echo "Файл $file не существует"
          fi
        done
