name: Sync to Yandex Cloud

on:
  push:
    branches:
      - master  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Yandex Cloud CLI
      run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        source "/home/runner/.bashrc"
        yc --version
        echo 'source /home/runner/yandex-cloud/completion.zsh.inc' >>  ~/.zshrc
        sudo mv /home/runner/yandex-cloud/yc /usr/local/bin/yc

    - name: Configure Yandex Cloud CLI
      env:
        YC_API_KEY: ${{ secrets.YC_API_KEY }}  
        YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
        YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
        YANDEX_BUCKET_NAME: ${{ secrets.YANDEX_BUCKET_NAME }}
      run: |
        yc config set service-account-key $YC_API_KEY
        yc config set cloud-id $YC_CLOUD_ID
        yc config set folder-id $YC_FOLDER_ID
        yc config set default-bucket $YANDEX_BUCKET_NAME

    - name: Upload changed files to Yandex Cloud
      run: |
        # Находим измененные файлы
        git diff --name-only HEAD^ HEAD | while read file; do
          # Загружаем измененные файлы в бакет Yandex Cloud
          yc storage cp $file "s3://$YANDEX_BUCKET_NAME/proj/$file" --recursive
        done
