name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - master  # или другая ветка, которую хотите отслеживать

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python (для работы с Yandex Cloud CLI)
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Yandex Cloud CLI
      run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        export PATH=$PATH:$HOME/.local/bin
        yc version
    
    - name: Authenticate with Yandex Cloud
      run: |
        echo "${{ secrets.YANDEX_CLOUD_KEY }}" > /tmp/key.json
        yc config profile create --name my-profile --service-account-key /tmp/key.json
        yc config set folder-id YOUR_FOLDER_ID
    
    - name: Upload files to Yandex Cloud Bucket
      run: |
        # Команда для загрузки файлов в бакет
        yc storage cp -r ./ ${Yandex_BUCKET_NAME}/${Yandex_FOLDER}/
      env:
        Yandex_BUCKET_NAME: ${{ secrets.YANDEX_BUCKET_NAME }}
        Yandex_FOLDER: ${{ secrets.YANDEX_FOLDER }}
