name: Sync to Yandex Cloud

on:
  push:
    branches:
      - master  # Укажите вашу ветку

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Для доступа к истории коммитов

    - name: Get changed files
      id: get_changed_files
      run: |
        files=$(git diff --name-only HEAD^ HEAD)
        echo "changed_files=$files" >> $GITHUB_ENV  # Записываем измененные файлы в переменную окружения

    - name: Debug git diff
      run: |
        git diff --stat ${{ github.event.before }} ${{ github.event.after }}
        git diff ${{ github.event.before }} ${{ github.event.after }} --name-status

    - name: Upload files
      env:
        YC_BUCKET: ${{ secrets.YANDEX_BUCKET_NAME }}
        YC_DIR: "proj/"  # Замените на вашу директорию
        CHANGED_FILES: ${{ env.changed_files }}  # Передаем измененные файлы как переменную окружения
      run: |
        if [ -z "$CHANGED_FILES" ]; then
          echo "Нет измененных файлов"
          exit 0
        fi
        for file in $CHANGED_FILES; do
          if [ -f "$file" ]; then
            aws s3 cp "$file" "s3://${YC_BUCKET}/${YC_DIR}${file}"
          fi
        done
